version: "3"
services:
    front3:
        build:
            dockerfile: Dockerfile.dev 
            context: ./front3
        volumes: 
            - /app/node_modules
            - ./front3:/app
        ports:
            - "3000:3000"
            